name: "checks"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  NODE_VERSION: "12.x"

jobs:
  checks:
    name: checks (build, lint, test)
    runs-on: ubuntu-latest
    env:
      COVERAGE_FOLDER: coverage
      REPORTS_FOLDER: reports
      BUILD_FOLDER: dist
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Check cache of yarn dependencies
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: npm run build:prod

      - name: Create reports folder
        run: mkdir $REPORTS_FOLDER

      - name: Lint code
        run: npm run lint:ci

      - name: Lint style
        run: npm run lint:style:ci

      - name: Run unit tests with coverage
        run: npm run test:ci

      - name: Coveralls unit tests
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN  }}
          flag-name: unit-tests
          path-to-lcov: ${{ env.COVERAGE_FOLDER }}/ut/lcov.info
          parallel: true

      - name: Run End-to-End tests with coverage
        run: npm run e2e:ci

      - name: Coveralls unit tests
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN  }}
          flag-name: e2e-tests
          path-to-lcov: ${{ env.COVERAGE_FOLDER }}/e2e/lcov.info
          parallel: true

      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

      - name: Upload coverage reports
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: ${{ env.COVERAGE_FOLDER }}

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ${{ env.BUILD_FOLDER }}
